/**
 * File generated by Magnet rest2mobile 1.1 - Oct 1, 2015 12:58:30 PM
 *
 * @see {@link http://developer.magnet.com}
 */

package io.c0nnector.github.tictailcontacts.api.model;


import android.support.annotation.ColorInt;

import org.parceler.Parcel;

import java.util.HashMap;
import java.util.Map;

import io.c0nnector.github.tictailcontacts.misc.Constants;
import io.c0nnector.github.tictailcontacts.util.Strings;
import io.c0nnector.github.tictailcontacts.util.UtilColor;
import io.c0nnector.github.tictailcontacts.util.Val;

/**
 * { "first_name" : "Jens", "last_name" : "Wirf", "title" : "", "color" : "4ec0d6", "image" :
 * "https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2014-09-29/2727982212_192.jpg",
 * "location" : "Europe/Stockholm", "team" : "Data", "id" : "a1ac0767-2999-4dea-b9a7-fea1b71362d9"
 * }
 */

@Parcel
public class Contact {


    String color;


    String first_name;


    String id;


    String image;


    String last_name;


    String location;


    String team;


    String title;

    public String getColor() {
        return color;
    }

    public String getFirst_name() {
        return first_name;
    }

    public String getId() {
        return id;
    }

    public String getImage() {
        return image;
    }

    public String getLast_name() {
        return last_name;
    }

    public String getLocation() {
        return location;
    }

    public String getTeam() {
        return team;
    }

    public String getTitle() {
        return title;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public void setColor(@ColorInt int color) {
        this.color = UtilColor.convert(color);
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public void setTeam(String team) {
        this.team = team;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getName() {
        return first_name + " " + last_name;
    }

    public int getColorInt() {
        return UtilColor.convert(color);
    }

    public boolean hasColor() {
        return Val.notNull(color);
    }

    /**
     * Creates a hashmap with contact params.
     *
     * @return
     */
    public Map<String, String> getAsMap() {

        Map<String, String> params = new HashMap<>();

        params.put("id", id);
        params.put("first_name", first_name);
        params.put("last_name", last_name);
        params.put("image", Strings.isNotBlank(image) ? image : Constants.URL_DUMMY_PHOTO); // allow empty urls
        params.put("location", location);
        params.put("team", team);
        params.put("title", title);
        params.put("color", color);

        return params;
    }

    public boolean equals(Contact contact) {
        return getAsMap().hashCode() == contact.getAsMap().hashCode();
    }

    public Contact clone() {

        Contact contact = new Contact();

        contact.color = this.color;
        contact.first_name = this.first_name;
        contact.id = this.id;
        contact.image = this.image;
        contact.last_name = this.last_name;
        contact.location = this.location;
        contact.team = this.team;
        contact.title = this.title;

        return contact;
    }

}
