/**
 * File generated by Magnet rest2mobile 1.1 - Oct 1, 2015 12:58:30 PM
 * @see {@link http://developer.magnet.com}
 */

package io.c0nnector.github.tictailcontacts.api.model;


import java.util.HashMap;
import java.util.Map;

/**
{
  "first_name" : "Jens",
  "last_name" : "Wirf",
  "title" : "",
  "color" : "4ec0d6",
  "image" : "https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2014-09-29/2727982212_192.jpg",
  "location" : "Europe/Stockholm",
  "team" : "Data",
  "id" : "a1ac0767-2999-4dea-b9a7-fea1b71362d9"
}
 */

public class Contact {

  
  private String color;

  
  private String first_name;

  
  private String id;

  
  private String image;

  
  private String last_name;

  
  private String location;

  
  private String team;

  
  private String title;

  public String getColor() {
    return color;
  }

  public String getFirst_name() {
    return first_name;
  }
  public String getId() {
    return id;
  }
  public String getImage() {
    return image;
  }
  public String getLast_name() {
    return last_name;
  }
  public String getLocation() {
    return location;
  }
  public String getTeam() {
    return team;
  }
  public String getTitle() {
    return title;
  }


  /**
   * Creates a hashmap with the contact params.
   * @return
   */
  public Map<String, String> getAsMap(){

    Map<String, String> params = new HashMap<>();

    params.put("id", id);
    params.put("first_name", first_name);
    params.put("last_name", last_name);
    params.put("image", image);
    params.put("location", location);
    params.put("team", team);
    params.put("title", title);
    params.put("color", color);

    return params;
  }

}
